version: "3.7"

services:

  server:
    image: milio1985/socket-test:v0.8
    ports:
      - 8888:8888
    depends_on:
      - "mysql"
    environment:
      PORT: '8888'	
      HOST_DB: 'mysql'
      USER_DB: 'Breathe_test'
      PASS_DB: '1234'
      DATABASE: 'OBU_readings'
      TABLENAME: 'frame_measures'
      DATA_STRUCTURE: '{ "VALID_DATA":       {"nbytes": 1, "type": "Validation", "div": 1, 
                                                   "map": {
                                                        "7":["PARTICLES_1", "PARTICLES_2_5", "PARTICLES_4", "PARTICLES_10"],
                                                        "6":["GASES_CO"],
                                                        "5":["GASES_NO2"],
                                                        "4":["GASES_SO2"],
                                                        "3":["GASES_O3"],
                                                        "2":["TEMPERATURE", "HUMIDITY"],
                                                        "1":["CO2"],
                                                        "0":["GPS_LATITUDE", "GPS_LONGITUDE"]
                                                    }
                                                },
                        "PARTICLES_1":      {"nbytes": 2, "type": "Int", "div": 10},
                        "PARTICLES_2_5":    {"nbytes": 2, "type": "Int", "div": 10},
                        "PARTICLES_4":      {"nbytes": 2, "type": "Int", "div": 10},
                        "PARTICLES_10":     {"nbytes": 2, "type": "Int", "div": 10},
                        "GASES_CO":         {"nbytes": 2, "type": "Int", "div": 10},
                        "GASES_NO2":        {"nbytes": 2, "type": "Int", "div": 10},
                        "GASES_SO2":        {"nbytes": 2, "type": "Int", "div": 10},
                        "GASES_O3":         {"nbytes": 2, "type": "Int", "div": 10},
                        "TEMPERATURE":      {"nbytes": 2, "type": "Int", "div": 10},
                        "HUMIDITY":         {"nbytes": 2, "type": "Int", "div": 10},
                        "CO2":              {"nbytes": 2, "type": "Int", "div": 10},
                        "GPS_LATITUDE":     {"nbytes": 4, "type": "Int", "div": 100000},
                        "GPS_LONGITUDE":    {"nbytes": 4, "type": "Int", "div": 100000},
                        "BATTERY":          {"nbytes": 0, "type": "Flag", "nbits": 7, "initpos": 2, "div": 1},
                        "SOURCE" :          {"nbytes": 1, "type": "Flag", "nbits": 1, "initpos": 1, "div": 1}
                        }'
      BYTES_FRAME: 'true'
      LITTLE_ENDIAN: 'false'

  mysql:
    image: mariadb:10.3.37
    volumes:
      - /home/pi/Desktop/mariadb:/var/lib/mysql
    environment:
      MARIADB_PASSWORD: 1234
      MARIADB_ROOT_PASSWORD: 1234
      
